### ISSUE TITLE
GitHub link incorrect on UI

### ISSUE THREAD

**Issue by SinclairKS** [p410n3/YDL-UI#2]
Encountered on the 1.0 release.

The GitHub link back to this project on the UI seems to be pointing to a non-existent project.

https://github.com/p410n3/Youtube-dl-PHP-GUI (404)

should be

https://github.com/p410n3/YDL-UI

**Comment by p410n3** [comment]
Will fix this right now in master, but this is so minor I wont make an extra release.

Thanks for the heads up!! 

EDIT: Fixed in https://github.com/p410n3/YDL-UI/commit/06b1d4173ac94c393c7338abd1d967c68c0741fd
