### ISSUE TITLE
Downloading...

### ISSUE THREAD

**Issue by Provokan** [p410n3/YDL-UI#4]
Guten Tag, 

ich kriege die "cmd" vom Downloading nicht angezeigt, er bleibt einfach auf der Seite wo man die URL eingibt und springt nach Beendigung direkt auf die Download Seite.  

URL: yt.provo.ovh
user: s****
pw: sie***

Es läuft auf folgenden Configurationen 

Debian 8 - Plesk 
PHP 7.0.25
Nginx&Apache

**Comment by p410n3** [comment]
Hi,

das problem haben mittlerweile mehrere Leute geäußert und es tritt in verschiedensten Variationen auf. Manchmal funktioneren deshalb downloads vn playlists nicht, bei dir scheint es "nur" probleme mit dem ob_flush zu geben, 

Ich werde aber wohl den live download ausstellen und einen alternativen weg wählen der leider nicht so hübsch ist, aber einheitlich funktioniert. Ich könnte natürlich dafür sorgen das es unter allen PHP versionen gleich funktioniert so wie geplant, allerdings habe ich für sowas weder zeit noch die nerven. Update sollte heute fertig sein. 

Danke für den Bug report!

**Comment by Provokan** [comment]
Wir wäre es mit einem circle der bis zu 100% geht?

**Comment by p410n3** [comment]
> Wir wäre es mit einem circle der bis zu 100% geht?

Ist momentan nicht in Planung. Solche features nehmen veil mehr aufwand in anspeuch als man glaubt. 

Ich habe mich trotzdem mal an einer lösung versucht, probier die doch mal aus.

Ist im neuen release.

https://github.com/p410n3/YDL-UI/commit/10bed1ccdad978b844351b62e185ce8b99940daa

**Comment by Provokan** [comment]
Guten Morgen, 

Habe dein neuen Release ausprobiert, jedoch erhalte ich beim erfolgreichen Download folgende Meldung

Kontra_K_-_Hunger_Official_Video-gW9HnkKf7Ps.mp3


Warning: Use of undefined constant Download - assumed 'Download' (this will throw an Error in a future version of PHP) in /var/www/vhosts/provo.ovh/yt.provo.ovh/php/loopAndPrint.php on line 12

Jedoch kann man trotzdem die MP3 File dann downloaden. :)

**Comment by p410n3** [comment]
Guten Morgen..
da ist mir aber ein Malheur passiert, ist behoben in https://github.com/p410n3/YDL-UI/commit/8eae7f308e6eea63f298dfbb1ee5d18e51ada47d 

Aber der übersicht halber nächstes mal in ein neues issue bitte, ist ja ein anderes problem :D

**Comment by Provokan** [comment]
Alles klar :) Close diesen dann hier 💃
