### ISSUE TITLE
Weird results from a Download request

### ISSUE THREAD

**Issue by mcat-ee** [p410n3/YDL-UI#5]
Hi!

When I use the app and try to download a video I get the following results:
![image](https://user-images.githubusercontent.com/2766980/37829044-7094e6c2-2eed-11e8-815d-4524efc06c60.png)

I initially installed master but then checked out 1.2 and i'm using the default credentials.

YDL-UI is running on a small AWS LightSail instance initialised with a LAMP stack.

**Comment by Provokan** [comment]
Hello,

your problem is solved as follows, please look in your root directory that the folders / php and / css and / js exist and there are the right files in there

**Comment by mcat-ee** [comment]
The directory layouts seem to match the structure of the git repository :(

**Comment by p410n3** [comment]
Make sure to make the owner of the folder to your webservers user (e.g. apache or www-data) and set permissions as 775

You can use either CHOWN and CHMOD
Or use an FTP client such as winSCP

Also always set it recursive

If not done the script is unable to use makedir and chdir thus the loopAndPrint.php script is executed inside the wrong folder.

**Comment by mcat-ee** [comment]
Hmmm i'm still struggling - I'll try again tomorrow!

I've used the following commands to set the permissions:
`sudo chmod 775 * -R`
`sudo chown www-data:www-data * -R`

**Comment by p410n3** [comment]
The folder itself isnt owned by the user that way.

Lets say your website is stored under /data/www/youtube
then do that:

```
cd /data/www
chmod -R 775 ./youtube
chown -R www-data:www-data ./youtube
```
In doubt, restart the webserver.

Also what PHP version are you runnning?

**Comment by p410n3** [comment]
@mcat-ee any news?

**Comment by p410n3** [comment]
I inspected that bug now and could onyl reporduce when using wrong user / file permissions. As the OP does not reply and I did not find  way to reporduce otherwiese, I will close that now
